### ISSUE TITLE
kdtree help: preanalysed dataset location

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#114]
In the grand scheme of sharing pre-baked datasets for demo examples across CCE (which is a great idea) I think we should put them in the core repo for 2 reasons

1. like in https://github.com/flucoma/flucoma-max/pull/110 it saves duplication
2. like anything that will rely on audio loading like this, we could make it sturdy to changes in the audiofile folder by making a labelset of the actual files loaded in that dataset so we are consistent upon reload.

**Comment by jamesb93** [comment]
I agree. How does this work for iterating on a local version of the package? I usually run `ninja` not `ninja install` so I don't get a release-packaging version. Would `misc` (the location of these datasets for Max) be able to be populated by that?

I don't think I have the `CMake`-fu to make it all work by myself so I would need some help from @weefuzzy or he could do it himself if its faster than holding me hand. Or he might have other ideas alongside @tedmoore.

**Comment by jamesb93** [comment]
Solved in #126
