### ISSUE TITLE
Launch Button in Max Package Manager

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#119]
I tested this Launch button in my Max Package Manager and it did launch for me, so maybe it is fine. 

But since one of our users said they were having a problem with it, the next time you're in Max can you just check and see if it works for you?

If it works for everyone, I'll close this!

<img width="1342" alt="Screenshot 2022-01-26 at 12 45 24" src="https://user-images.githubusercontent.com/1531144/151218074-5b56c893-79ec-450f-b585-c3a263ce03c5.png">

**Comment by weefuzzy** [comment]
Yup, working here too. If you're in correspondence with the afflicted person again, perhaps they could supply more information? (I'll check on Windows too, next time I'm there...)

**Comment by jamesb93** [comment]
Works for me.

**Comment by weefuzzy** [comment]
Working in Windows too
