### ISSUE TITLE
Dataset~ write message

### ISSUE THREAD

**Issue by jdchart** [flucoma/flucoma-max#125]
Hello,

When writing a dataset~ to disk, I need to manually add the extension .json for it to be able to be selected in the open dialog when sending the "read" message.

Should probably be default when writing, or maybe add a "writejson" message like buffer~, or just signal in the docs?

Thanks,

**Comment by jamesb93** [comment]
Dataset's should write by default as `.json` and I think it's fair to assume someone will load `.json` as a result and not anything without an extension or another format.
