### ISSUE TITLE
fluid.chroma~ and additional arbitrary values when reducing the number of outputs

### ISSUE THREAD

**Issue by AlexHarker** [flucoma/flucoma-max#15]
using fluid.chroma~ in max and reducing the number of chroma bins leads to an output of the same size of max_chroma (as in the helpfile) but the last values are repeats of the old values from before reducing, and not zeros (which is not what I expect).
 
Latest beta - fluid.chroma~: Fluid Corpus Manipulation Toolkit, version 1.0.0-TB2.beta2

**Comment by tremblap** [comment]
sorted in the new beta.
