### ISSUE TITLE
non-install compile does not have links/copies/whatever to fluid.waveform

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#163]
this makes dev complicated - this is an ongoing discussion on all CCEs on how to make the best dev workflow...

**Comment by weefuzzy** [comment]
This was a deliberate choice. At least, in part, because we don't want to end up needing npm etc for this repo.

The way I do it is to have an alias to the max package of `fluid.waveform` in my `Packages` folder:
```
~/Documents/Max 8/Packages
├── flucoma-max
└── fluid.waveform -> /Users/owen/fluid.waveform/max-package
```
