### ISSUE TITLE
BufCompose "macros" need a home

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#166]
BufCompose macros that used to live in the bufcompose help file need a place to live. I think that a sensible place would be a vignette for the object, maybe back in the help file (with some refactoring and cleaning up) or in the tutorial system.

**Comment by tremblap** [comment]
there was also a lot of advance examples that have disappeared. we can make the list before they are forgotten...

**Comment by jamesb93** [comment]
> there was also a lot of advance examples that have disappeared. we can make the list before they are forgotten...

merge, stack, concatenate

They live in the git history forever.

**Comment by tremblap** [comment]
as do all the other deleted examples I am referring to (invert stereo and power edits and even the MS ones which had been put back to the example folder already)

**Comment by jamesb93** [comment]
> as do all the other deleted examples I am referring to (invert stereo and power edits and even the MS ones which had been put back to the example folder already)

Oh yeah these ones.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/13281862/159752610-be193c0d-c692-425e-890f-98305e987a56.png">

My feeling was these are really idiosyncratic advanced use cases. Vignettes would be more appropriate.

**Comment by jamesb93** [comment]
Snippets are a good place to put these.

**Comment by jamesb93** [comment]
Solved in feb349c
