### ISSUE TITLE
Help file layout is inconsistent with rest of Max

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#167]
Help files currently have the full `helpdetails.js` at the top of the patchers. The first tab should have this, with the digest stripped out for subsequent patchers.

Check `groove~` for a reference.

**Comment by rconstanzo** [comment]
There's also a quite different overall "style" with loads of colors and boxes and such, vs vanilla/native objects (`fluid.dataset~` is perhaps a decent example).

**Comment by jamesb93** [comment]
This is largely taken care of with the various revisions of help files that have been going on this week.
