### ISSUE TITLE
fluid.waveform~ help file is committed into history

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#168]
Hard to verify which copy is being used on github actions. The version from the other repo should be pulled in and placed in the correct location. We should verify before we merge dev to branch for beta6 whether or not this is happening as imagined.

**Comment by weefuzzy** [comment]
We can certainly pull it to the right place on install. Presently that's all that happens with the waveform stuff, and we assume that if you're developing you have your own working copy of the waveform~ repo. So: 

* delete the helpfile from this repo
* we update the CMake to make sure the proper helpfile is installed in <package>/help at install time

yas?

**Comment by jamesb93** [comment]
Yaaaaaassss!

**Comment by jamesb93** [comment]
Solved in #169
