### ISSUE TITLE
fluid.datasetquery~ helpfile typo

### ISSUE THREAD

**Issue by AlexHarker** [flucoma/flucoma-max#17]
At the top of the combining columns tab:

"transformjoin <dataset A> <dataset B> <desintation dataset>"

"destination" is mistyped.

**Comment by jamesb93** [comment]
This is solved now. I couldn't see the transformjoin typo though but destination was obvious. If possible can you send a screenshot or even better pull to the tip and see if the problem persists?

**Comment by AlexHarker** [comment]
I wrote the report pretty quickly, but given that the title is "typo" (singular) I'm sure that I just put transformjoin in to point to the right place in the patch - it's just the word destination that was mistyped - I'm happy to accept this as done if you want to close.

**Comment by jamesb93** [comment]
Same. Thanks 🚀
