### ISSUE TITLE
fluid.plotter~ landing tab default data

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#172]
The helpfile's landing tab loads default data, but most of it is out of range, so not visible.

<img width="1553" alt="Screenshot_2022-03-30_at_14 42 34" src="https://user-images.githubusercontent.com/1531144/160849073-b7e614a1-e8b7-4aec-b224-69422a7e1238.png">

**Comment by tremblap** [comment]
I reported this in issue 162
