### ISSUE TITLE
Max Reference (nor help file) contain info on which integers correspond to which Activation Funtions

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#179]
This seems too be true for both `@activation` and `@outputactivation`

<img width="947" alt="Screenshot 2022-04-19 at 18 07 03" src="https://user-images.githubusercontent.com/1531144/164109649-5ee4d89b-19d8-43a8-98dc-9eeaf215926d.png">

**Comment by jamesb93** [comment]
This seems to work now!

![image](https://user-images.githubusercontent.com/13281862/173337214-cfbb76ad-c353-457b-9138-554267b2a7b0.png)
