### ISSUE TITLE
Building it with gcc on Windows

### ISSUE THREAD

**Issue by 11ols** [flucoma/flucoma-max#18]
Hi, I'm trying to build this on my own because my cpu seems to lack AVX support. I'm not using visual studio but in the cmake files for the single projects the Visual Studio flag /wd4814 is added which, in my case leads to an error while building.
![grafik](https://user-images.githubusercontent.com/21139297/122889270-eea49d80-d342-11eb-850e-3afe7e2e9baf.png)
Is it possible to disable the addition of this flag? Thank you, O.

**Comment by weefuzzy** [comment]
Thanks for the report. I can't guarantee that this will build with MinGW and I can't test at the moment. We've just had cross messages, and I've already responded on our discourse, but the problem here (I expect more) is one line 99 of `source/script/max-posttarget.cmake`. 

The quick and dirty thing to try is just commenting it out. The fix I will eventually push once I can test it will look more like 
```cmake
  if(MSVC)
	   set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "/wd4814")
  endif()
```

**Comment by 11ols** [comment]
It went really well, around 70% through, then stops at fluid.libmanipulation without giving me any error description:

```
make[2]: *** [source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/build.make:63: source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/fluid.libmanipulation.cpp.obj] Fehler 1

make[1]: *** [CMakeFiles/Makefile2:2113: source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/all] Fehler 2

make: *** [Makefile:130: all] Fehler 2
```

**Comment by weefuzzy** [comment]
Arg! Does any sort of log file appear in your `build` folder? 

`fluid.libmanipulation` is distinctive insofar as it bundles together a bunch of externals that need to talk to each other, but that shouldn't be a problem in and of itself. I wonder if the .o file ends up being too big? (This is total guesswork). 

Here's something to try (again, apologies – I'd try this myself if I had a working Windows environment just at the moment) 

In your source folder edit `source/projects/fluid.libmanipulation/CMakeLists.txt`

At the end (line 12) try adding 

```cmake 
target_compile_options(${PROJECT_NAME} PRIVATE "-Wa,-mbig-obj")
```

**Comment by 11ols** [comment]
No success either after adding the line. I noticed errors scrolling by before it stops:

![grafik](https://user-images.githubusercontent.com/21139297/122931866-8fa84e00-d36d-11eb-872a-a00af8fb3e42.png)

strange that compiling doesn't stop immidiately on this errors.

**Comment by 11ols** [comment]
returns:
g++.exe (Rev1, Built by MSYS2 project) 8.2.1 20181214
Copyright (C) 2018 Free Software Foundation, Inc.

**Comment by weefuzzy** [comment]
Ok that should be new enough. The dependency in question ships with tests, so we should be able to try and build *those* and see if we're any the wiser, if you're up for it. Just building them here to get the commands straight in my head, but can you look in the `_deps` subdirectory of your `build` directory and see if you see something like `spectra-src` and `eigen-src`?

**Comment by 11ols** [comment]
I have an empty spectra-src folder and no eigen-src in there. I had to download spectra, eigen, hisstools and flucoma-core manually and put them to the root folder. In cmake-gui I entered the paths to them. 

![grafik](https://user-images.githubusercontent.com/21139297/122965910-04d54c80-d389-11eb-89a8-d549eaa94f11.png)

I don't want to generate any effort for you and in the end it's a weakness of the MSYS2 Env. I already had problems with min-dev-kit and this compile method.

**Comment by weefuzzy** [comment]
Ouch. Sorry this has been such a mission. 

Fortunately building the Spectra tests is very similar to building our stuff, and it might help us work out what's not working at our end. 

If you go to your spectra folder and do 
```bash 
mkdir build 
cd build 
cmake -DEigen3_ROOT=<Your Eigen Folder As Shown Above> -DBUILD_TESTS=ON ..
make 
```
then if it builds we've got a difference to look for, and if it doesn't hopefully we get a better error message 🤞

**Comment by 11ols** [comment]
I'm confused. 
![grafik](https://user-images.githubusercontent.com/21139297/122981559-2e4aa400-d39a-11eb-9f10-5bbd33c40fae.png)

**Comment by weefuzzy** [comment]
Lol me too. Does that mean it couldn't find a makefile? Can you run `ls` in the build directory?  I get 
```
CMakeCache.txt
CMakeFiles
CTestTestfile.cmake
Makefile
cmake
cmake_install.cmake
test
```
where CMakeFiles, cmake and test are folders

**Comment by 11ols** [comment]
I deleted the build dir and did it again. Actually, it's creating Visual Studio projects in there on the first run.

```
$ cmake -DEigen3_ROOT="C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucoma-max-1.0.0-TB2.beta2/eigen-master" -DBUILD_TESTS=ON ..
-- Building for: Visual Studio 12 2013
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:24 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable Eigen3_ROOT is set to:

    C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucoma-max-1.0.0-TB2.beta2/eigen-master

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Eigen3 Version: 3.3.7 Path: C:/msys64/mingw64/share/eigen3/cmake
-- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is at least "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
-- The following REQUIRED packages have been found:

 * Eigen3
   C++ vector data structures

-- The following OPTIONAL packages have not been found:

 * CLANG_FORMAT (required version >= 9)

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucoma-max-1.0.0-TB2.beta2/spectra-master/build

```
Here's the build folder:

![grafik](https://user-images.githubusercontent.com/21139297/122995332-c8661880-d3a9-11eb-8972-23dac829e99a.png)

**Comment by weefuzzy** [comment]
Oh, right. How confusing! Do you actually have MSVC installed then? Is that also what it did for the FluCoMa project? (Doesn't look like it above)

You can build the MSVC project without opening VS with `cmake --build .` (but this would – I guess – run msbuild, not g++). 

If you want a makefile instead (to build with GCC) then you'll need to scrub the build folder and rerun cmake with `-G"Unix Makefiles" added to the options.

**Comment by 11ols** [comment]
Yes, I also have visual studio 2013 installed. I once started using netbeans and gcc to be able to compile clang and C99 conform code on Windows. And a quick search tells me VS is still not supporting C99 these days. Or is it when I change the compiler in VS ? I have to investigate on this. Even the fact that I could use cmake in VS is new for me. The -G"Unix Makefiles" flag works. I'm going to give it another try tomorrow and will eventually install VS2019 and try that route. At the end it is more important to make it run somehow than to get it done with g++. Thanks so much for your patience weefuzzy

**Comment by 11ols** [comment]
I reinstalled the complete msys2 and now the fetchcontent process is working again, but when the dependency is loaded from git it stops. This is the output after fetching flucoma-core:

```
Populating flucoma-core
-- Configuring done

-- Generating done

-- Build files have been written to: C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-max-1.0.0-TB2.beta2/build/_deps/flucoma-core-subbuild

[ 11%] [34m[1mPerforming update step for 'flucoma-core-populate'[0m

CMake Error at C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-max-1.0.0-TB2.beta2/build/_deps/flucoma-core-subbuild/flucoma-core-populate-prefix/tmp/flucoma-core-populate-gitupdate.cmake:25 (message):

  Failed to get the hash for HEAD:

  fatal: ambiguous argument 'HEAD^commit': unknown revision or path not in
  the working tree.

  Use '--' to separate paths from revisions, like this:

  'git <command> [<revision>...] -- [<file>...]'




make[2]: *** [CMakeFiles/flucoma-core-populate.dir/build.make:136: flucoma-core-populate-prefix/src/flucoma-core-populate-stamp/flucoma-core-populate-update] Error 1

make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/flucoma-core-populate.dir/all] Error 2

make: *** [Makefile:91: all] Error 2

CMake Error at C:/msys64/mingw64/share/cmake-3.20/Modules/FetchContent.cmake:1012 (message):
  Build step for flucoma-core failed: 2
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.20/Modules/FetchContent.cmake:1141:EVAL:2 (__FetchContent_directPopulate)
  C:/msys64/mingw64/share/cmake-3.20/Modules/FetchContent.cmake:1141 (cmake_language)
  CMakeLists.txt:69 (FetchContent_Populate)


Configuring incomplete, errors occurred!
See also "C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-max-1.0.0-TB2.beta2/build/CMakeFiles/CMakeOutput.log".

```
If your time allows, do you have an idea to solve this?

**Comment by weefuzzy** [comment]
Not something I've seen before, but it seems you've hit a very recent cmake + msys bug with FetchContent: https://gitlab.kitware.com/cmake/cmake/-/issues/22299

The workaround (I guess) would be either: 
–  to go to `flucoma-core-populate-gitupdate.cmake:25` and change `"${ref}^{commit}"
` to `"${ref}^0"`
– stick with the manual dependencies you already downloaded
```
cmake -DMAX_SDK_PATH=<whatever> -DFLUID_PATH<what you downloaded> -DHISS_PATH=<and again> -DEIGEN_PATH=<and again> -DSPECTRA_PATH=<and again> -DFLUID_ARCH=-mcpu=native -G"Unix Makefiles" ..
```
😅

**Comment by 11ols** [comment]
I can build spectra but not flucoma-max. Stops at fluid.libmanipulation like before. I'll give up for now

**Comment by weefuzzy** [comment]
> I'll give up for now

Ah, I'm sorry this has been such a schlep. If you do decide to return to it, then I think there's a clue in Spectra building its tests ok, buried in the CMake file for the tests themselves. 

A thing to try would be to edit CMakeLists.txt for flucoma-core at the block starting line 166, to say: 
```cmake 
if(CMAKE_COMPILER_IS_GNUCXX)
  target_compile_options(
    FLUID_DECOMPOSITION INTERFACE -fpermissive -Wno-int-in-bool-context
  )
endif()
```
This is still guessing until I get a working Windows environment again, but chimes with both the error you got and the fact that this seems to be something making g++ unhappy (although we've not had these problems on Linux 🤷)

**Comment by 11ols** [comment]
No, that didn't make any change. I added -w to remove warnings and at least I see all errors now:

```
[ 68%] Building CXX object source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/fluid.libmanipulation.cpp.obj
g++.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
In file included from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/public/UMAP.hpp:5,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/data/FluidJSON.hpp:9,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/clients/nrt/DataClient.hpp:15,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/clients/nrt/DataSetClient.hpp:12,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-max-1.0.0-TB2.beta2/source/projects/fluid.libmanipulation/fluid.libmanipulation.cpp:3:
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp: In member function 'fluid::algorithm::SpectralEmbedding::ArrayXXd fluid::algorithm::SpectralEmbedding::train(fluid::algorithm::SpectralEmbedding::SparseMatrixXd, fluid::index)':
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:35:27: error: 'SMALLEST_MAGN' was not declared in this scope
   35 |     SymEigsSolver<double, SMALLEST_MAGN, SparseSymMatProd<double>> eig(&op, k,
      |                           ^~~~~~~~~~~~~
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:35:65: error: wrong number of template arguments (3, should be at least 0)
   35 |     SymEigsSolver<double, SMALLEST_MAGN, SparseSymMatProd<double>> eig(&op, k,
      |                                                                 ^~
In file included from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:5,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/public/UMAP.hpp:5,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/data/FluidJSON.hpp:9,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/clients/nrt/DataClient.hpp:15,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/clients/nrt/DataSetClient.hpp:12,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-max-1.0.0-TB2.beta2/source/projects/fluid.libmanipulation/fluid.libmanipulation.cpp:3:
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/spectra-master/include/Spectra/SymEigsSolver.h:134:7: note: provided for 'template<class OpType> class Spectra::SymEigsSolver'
  134 | class SymEigsSolver : public SymEigsBase<OpType, IdentityBOp>
      |       ^~~~~~~~~~~~~
In file included from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/public/UMAP.hpp:5,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/data/FluidJSON.hpp:9,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/clients/nrt/DataClient.hpp:15,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/clients/nrt/DataSetClient.hpp:12,
                 from C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-max-1.0.0-TB2.beta2/source/projects/fluid.libmanipulation/fluid.libmanipulation.cpp:3:
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:37:9: error: request for member 'init' in 'eig', which is of non-class type 'int'
   37 |     eig.init(initV.data());
      |         ^~~~
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:38:27: error: request for member 'compute' in 'eig', which is of non-class type 'int'
   38 |     auto nConverged = eig.compute(
      |                           ^~~~~~~
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:40:25: error: request for member 'eigenvectors' in 'eig', which is of non-class type 'int'
   40 |     mEigenVectors = eig.eigenvectors();
      |                         ^~~~~~~~~~~~
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:41:24: error: request for member 'eigenvalues' in 'eig', which is of non-class type 'int'
   41 |     mEigenValues = eig.eigenvalues();
      |                        ^~~~~~~~~~~
At global scope:
cc1plus.exe: note: unrecognized command-line option '-Wno-gnu-zero-variadic-macro-arguments' may have been intended to silence earlier diagnostics
make[2]: *** [source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/build.make:76: source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/fluid.libmanipulation.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1998: source/projects/fluid.libmanipulation/CMakeFiles/fluid.libmanipulation.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by weefuzzy** [comment]
```
C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp:35:27: error: 'SMALLEST_MAGN' was not declared in this scope    
```

Huh. Maybe this compiler is being ultra fussy about namespaces? Looking at the source, `SMALLEST_MAGN` should be covered by `using namespace spectra` at the top of the function. 

What if in `C:/Users/ols/Dropbox/11OLSEN/NOT oLsen/flucomaNew/flucoma-core-main/include/algorithms/util/SpectralEmbedding.hpp` you change the two mentions of `SMALLEST_MAGN` (lines 35 & 39) to `Spectra::SMALLEST_MAGN`? 

(I'm just trying to get MSYS to play nicely on VirtualBox, at which point I might be better placed to offer some less hypothetical help)

**Comment by 11ols** [comment]
That leads to: 'SMALLEST_MAGN' is not a member of 'Spectra'. 

> I'm just trying to get MSYS to play nicely

If it helps: after msys2 installation I updated and  installed toolchain, cmake, git and qt5 for cmake-gui with pacman.

**Comment by weefuzzy** [comment]
> 'SMALLEST_MAGN' is not a member of 'Spectra'.
Gah, it  certainly is! Seems like something weird is going on. 

> If it helps: after msys2 installation I updated and installed toolchain, cmake, git and qt5 for cmake-gui with pacman.

I did the toolchain, cmake and git. At the moment cmake isn't generating compiler commands with any include paths, but I've also had to ask extra nicely for it to treat the machine as x64, so something is definitely unhappy. 

On the brighter side, now that I've resurrected this VirtualBox I might just be able produce some non-AVX externals  with MSVC 😄

**Comment by 11ols** [comment]
> I might just be able produce some non-AVX externals with MSVC
hey that's cheating, but yes that would help, too.;-)

**Comment by weefuzzy** [comment]
I know, right 😄 No staying power. I've DM'd you a link to a build on discourse. Feel free to return to the joys of figuring out a Mingw build, but I wanted you to at least get to play with some stuff!

**Comment by jamesb93** [comment]
I think given we no longer compile with AVX by default this is is no longer a problem for the masses but a niche one of compiling with those instruction sets enabled. I'll close for now and we can improve documentation for this sort of thing :)
