### ISSUE TITLE
fluid.waveform~ crashes max8 when adding markers

### ISSUE THREAD

**Issue by tothbar** [flucoma/flucoma-max#180]
Just crashes my max, every time i try to load markers

**Comment by felipevaz** [comment]
same here, with MacOS 10.15.7, Max 8.2.1 -- I followed the "Building a 2D Corpus Explorer" tutorial in Youtube, and when clicking on the markers message, Max crashes

**Comment by jamesb93** [comment]
`markers` should be equivalent to `slices`. If you are getting a crash would you be able to provide the report that gets made with it?

**Comment by jamesb93** [comment]
Ah!!! This is my bad.

I've added a pull request to fix it. In the meantime providing the name of the buffer that you sliced as the second argument to markers will work.

https://github.com/flucoma/fluid.waveform/pull/21
