### ISSUE TITLE
fluid.bufstats~ documentation

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#192]
As per the `@select` change, the `p resultsToDict` subpatch spits out `stddev`, which I assumed was what the corresponding `@select` symbol is, but it's `std` instead. The helpfile should reflect this change.

**Comment by jamesb93** [comment]
Thanks @rconstanzo I will be fixing this pretty quickly in https://github.com/flucoma/flucoma-max/pull/195

**Comment by rconstanzo** [comment]
Don't know what the eventual or planned naming will be, but it would be great to be able to use `std`, `stddv`, `deviation`, as well as `median`, `middle`, `mid`, or even the elusive `nummidmeanchanframes`.

Since the `@select` attribute is essentially taking abbreviations, it would be handy to have as many aliases as possible so people don't need to hunting to see what the naming is.

**Comment by jamesb93** [comment]
> Don't know what the eventual or planned naming will be, but it would be great to be able to use `std`, `stddv`, `deviation`, as well as `median`, `middle`, `mid`, or even the elusive `nummidmeanchanframes`.
> 
> Since the `@select` attribute is essentially taking abbreviations, it would be handy to have as many aliases as possible so people don't need to hunting to see what the naming is.

That seems less likely to me than having a set of fixed, singular arguments. I think that once you learn the magic words once then its easy to come to terms with it. I often cheat by right clicking the first inlet and inspecting the options this way:

![image](https://user-images.githubusercontent.com/13281862/167443748-49cf8362-3e27-4df9-927a-f4d3aa154a80.png)

**Comment by jamesb93** [comment]
Already fixed in latest documentation updates.
