### ISSUE TITLE
fluid.bufstats~ @warnings attributes ignores "yellow" messages

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#198]
So in my patch I have a processing chain that sets a `weights` buffer for each of my `fluid.bufstats~` objects. It works perfectly fine _but_ whenever Max recompiles the dsp chain (e.g. (dis)connecting an audio cable) my Max console is spammed with:

> fluid.bufstats~: Invalid weights
> fluid.bufstats~: Invalid weights
> fluid.bufstats~: Invalid weights
> fluid.bufstats~: Invalid weights
> fluid.bufstats~: Invalid weights
> fluid.bufstats~: Invalid weights

So I went back to add `@warnings 0` to each of them, but this has no impact on stuff.

Basically something upstream is banging when dsp is recompiled and I guess along the way the weights are cleared or something?

**Comment by rconstanzo** [comment]
Ok, it seems that when dsp is recompiled the analysis chain analyzes a silent moment (using the JIT analysis paradigm) and produces a weights buffer of `0. 0. 0. 0. 0. 0. 0.`.

Obviously that's not a useful weight, and after some testing it seems to only happen with all weights being equal and zero (i.e. doesn't happen with `1. 1. 1. 1. 1. 1. 1.`). Is there a reason why this specific set of values is treated differently? Surely it would be mathematically the same as any other set of equal values? (e.g. `1. 1. 1. 1. 1. 1. 1.` or `0.5 0.5 0.5 0.5 0.5 0.5 0.5`).

**Comment by weefuzzy** [comment]
> Surely it would be mathematically the same as any other set of equal values?

No. The weights need to be normalised to sum to 1 internally – this is impossible with a list of all zeroes (but nothing else). IOW, `0` does have a special significance here in that it means there is no probability of this thing ever being true. 

This warning being ignored by `@warnings` was a deliberate decision.

**Comment by rconstanzo** [comment]
Hmm, this leaves it in a weird limbo as if you analyze digital silence upstream (totally possible in many patches), you can end up with scaled loudness weights of 0 and it becomes unavoidable to get spammed with this warning. I guess I can set `@outputlow 0.0000001` in `fluid.bufscale~`, but that feels like a hacky workaround.

**Comment by rconstanzo** [comment]
Bumping this as:

![Screenshot 2022-06-21 at 3 59 27 pm](https://user-images.githubusercontent.com/2747015/174832038-bd1fb627-f4e5-4fe5-becc-c626b1fb92c6.png)

Once I do any amount of patching with a `fluid.bufstats~` in the chain, my Max console quickly looks like this:
![Screenshot 2022-06-21 at 3 58 07 pm](https://user-images.githubusercontent.com/2747015/174832199-d8e8788d-5590-4da3-a743-c5d735eb986f.png)

**Comment by rconstanzo** [comment]
Well, my "brilliant" workaround actually doesn't work here as what's being passed to `fluid.bufstats~` is a `buffer~`, and not a list of numbers. So short of adding an extra `fluid.buf2list` -> `fluid.list2buf` step for each match, which would add unnecessary for a weird edge case, there is no way to avoid this.

**Comment by rconstanzo** [comment]
I guess I just have a weird aversion to adding additional `buf2list` and `list2buf` steps as they happen up and down the chain for various reasons (e.g. not being able to concatenate individual descriptor buffs in a high priority thread), and I worry that the aggregate of having these points of conversions peppered throughout would impact the latency in appreciable way.

**Comment by rconstanzo** [comment]
All that being said, I don't see what's gained by excluding this type of warning from the `@warning` messages as it seems like this is exactly the kind of thing that that would be useful for (non-breaking, but annoying warnings).

**Comment by weefuzzy** [comment]
>  I worry that the aggregate of having these points of conversions peppered throughout would impact the latency in appreciable way

I think latency affects would only become acute if you ended up jumping between the main and scheduler threads a lot. Presumably, if you're taking advantage of the new buffer interface then you're doing ok sticking on the main thread for this particular stuff. 








> All that being said, I don't see what's gained by excluding this type of warning from the `@warning` messages as it seems like this is exactly the kind of thing that that would be useful for (non-breaking, but annoying warnings).

But our view is that this *is* more severe than the more informational warnings about just having attribute values clipped or whatever, because it means that the code just won't work. We were pretty close to making it an error instead (basically, it's a shame Max doesn't offer more verbosity levels). I know in this particular use case there's a straightforward interpretation of what 'it' means and what to do, but we didn't feel that carried over to the general case and that responsibility for how to interpret and work around 0-weights has to be left to the caller.

**Comment by rconstanzo** [comment]
Another potential issue here is that for whatever descriptors are being weighted (and subsequently blocked via the workaround) is that those entries don't exist further downstream, so if you have a `counter` down the pipeline that is packing stuff into a `fluid.dataset~` everything after this one point will be wrong in this "vertical".

Say you have pitch analysis, which isn't being loudness-weighted, that will still return an entry (albeit not a very useful one if it's a frame of silence). Now, you can just use this mechanism to block pitch too, but that doesn't work for loudness itself, where knowing an analysis window is silent (digital or otherwise) is actually very useful.

So blocking frames where the weighting data is silent is only just kicking the, proverbial, can further down the analysis road.

**Comment by weefuzzy** [comment]
Then don't block, but instead emit a default fall-back that makes sense for your particular analysis (like a buffer full of 0s). 

This doesn't seem connected to the issue of whether you get a warning or not, but whether or not `bufstats` is able to determine something universally sensible to do in this situation (it is not).

**Comment by rconstanzo** [comment]
> This doesn't seem connected to the issue of whether you get a warning or not, but whether or not `bufstats` is able to determine something universally sensible to do in this situation (it is not).

I guess the issue itself for me has morphed in to thinking that `fluid.bufstats~` should treat a weights buffer of zeros the same as any other equal-number set of weights (i.e. "don't apply any weighting").

> Then don't block, but instead emit a default fall-back that makes sense for your particular analysis (like a buffer full of 0s).

My example is more to point out that the workaround(s) require a level of knowledge, detail, and specificity that is perhaps a bit much for a regular user to dig in to. (e.g. having to manage auxiliary "just in case" buffers of zeros for cases where silent windows may be analyzed).

**Comment by weefuzzy** [comment]
> I guess the issue itself for me has morphed in to thinking that `fluid.bufstats~` should treat a weights buffer of zeros the same as any other equal-number set of weights (i.e. "don't apply any weighting").

If the issue has morphed, then can we close this one? If you want to put forward an argument as to why we ought not treat all 0s as degenerate and probably-a-mistake, then go for it (but in a new issue). 

> My example is more to point out that the workaround(s) require a level of knowledge, detail, and specificity that is perhaps a bit much for a regular user to dig in to. (e.g. having to manage auxiliary "just in case" buffers of zeros for cases where silent windows may be analyzed).

Who do you mean by regular user? A lot of the tool kit objects are low level and one would expect some ancillary plumbing around them when making any system that needed to be robust. The tools as they stand simply aren't aimed at beginners (if this is who a regular user is). The upside of them being low level is that ancillary plumbing for particular use cases like this can easily be built into abstractions. If general enough, then those abstractions could find their way back into the main tool kit, or could form the basis of a new project building on FluCoMa that simplifies some usage patterns at the cost of generality.

**Comment by rconstanzo** [comment]
> If you want to put forward an argument as to why we ought not treat all 0s as degenerate and probably-a-mistake, then go for it (but in a new issue).

#308 

> Who do you mean by regular user? A lot of the tool kit objects are low level and one would expect some ancillary plumbing around them when making any system that needed to be robust. The tools as they stand simply aren't aimed at beginners (if this is who a regular user is). The upside of them being low level is that ancillary plumbing for particular use cases like this can easily be built into abstractions. If general enough, then those abstractions could find their way back into the main tool kit, or could form the basis of a new project building on FluCoMa that simplifies some usage patterns at the cost of generality.

I don't mean in terms of knowledge/skill, more to that this is more of a technical edge case that requires behind-the-scenes thinking, rather than upfront knowledge by the user (IMO). Or put more plainly, the way the objects are built now means that there is audio that you can analyze that breaks the process:

<pre><code>
----------begin_max5_patcher----------
799.3ocuVssbaBCD8Y6uBM7LwitAH5S9+nSmLxfvVIXIFPD61LIe6ck.mFm3
1ZhcxKwQqVocOmytK5w4yhVY2q5hPeC8czrYONe1rfIugYiqmEsUtunV1EbK
ZqpqStVEEOrmSs2ErWoqqQ3EjCazzp5TFmzoslaq0FUgs2DbkN5goeqs2Uqb
gKlLZcvj6mMpgrJJB8iCWozUrQaVeaqpvMraFMaQdJgJDILVhPvSDwnLxBBI
gIH4rTFilQhQb7BbLhRWfe41fvqMGh9gbRWF.ic0c2jG4M8z749+DegrSmS1
5pZkaUHHOVIMqithrPBaAmCnkJvXlflJ.Rfm6QLAmNYfKtl.err3Zh1TA6rz
bFaxPO8i.ciZGb12g7U8UUp1mQNUmCzAL9zb.8uwAU0VoKJFtHe0xjIDBl+N
FIO+eyHj2yHrqHiTU2qKW.7BzM35dFsrSUCf.sUIMnkPlTpZ0OzgHSjo7jzj
6OnvHAFOkv4zbg.HuLNXLGuHAbLIICnLbRlm0l1TC9mBg0.XoUV2sQ1n7Dms
usPMTZsrpx0A7A.4NDMIEkxQIDJZIDA+V5eofwe4oAFtXiz.Db3+CiiFNxxF
6NUq2duQ67+1HKKgaDQeQkJfo4sVcIppV5LP69gz8ng67u.o6Tk1zz72qboS
oRmREeJRWgrNHY9u.3oeD9XkPaZ.VwtCcCLjXb4F85Md+Jp0MMdYfcRxldkI
aFkehAIBvHkgy3bLmmmiSow9hF+nDVxDH3rOE9s11W5qFeaWwqo3cZSocWnS
HTsCA3UlFZN1XaBqftmk2uSABfuixKBt1dUiRd+nvcTaygtjSJOruD44DMCr
gO84eBvYqNGM2Jbp.XdyaCCYk29wJ1.yOhigGOEi9SrKAEQaBOE7U9vF74j0
Dmab3mQbf5tKOPhyHPGmL1V3yY9cwWTf8ik9+gNm+Egw2lNufRxEE5ryFjjK
DjoenJygFBYSyCp1tQmCg.FVcmMP.h3vRsYXYn4OpU8f9f+gltHYKzV6fd59
1PZEsOkGMbTKPkld8HaBfCBYXPnwOwoQNfiv7x4OM+2.KncTUB
-----------end_max5_patcher-----------
</code></pre>

I don't think that should be the case.
