### ISSUE TITLE
Verbose information when hovering over outlets

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#2]
As per this forum thread:
https://discourse.flucoma.org/t/verbose-information-when-hovering-over-outlets/

When hovering over the outlets for Max objects, no information is given about the output, which is unlike most native Max objects.
![](https://discourse.flucoma.org/uploads/default/original/1X/1b68ebd8f9e548e90c0636ab144d2b6a4cc494df.png)

**Comment by weefuzzy** [comment]
Thanks @rconstanzo – first feature request! 

We agree this is needed. What's not clear to us yet is the urgency. The way we'd [I'd] want to do it calls for changes to [flucoma-core](https://github.com/flucoma/flucoma-core) that won't be at all immediate. If there is widespread desire for this, I could concieve of a less beuatiful way of patching it in this repo only.

**Comment by tremblap** [comment]
I can confirm this has been on the low priority todo list for some time... we agree it will help indeed but considering the complexity of the object's input, and the simplicity of the object's outputs (usually in the name!) then it definitely does not feel like an emergency :)

**Comment by rconstanzo** [comment]
It's more like for things like `fluid.hpss~`, I never know which outlet has the harmonic and percussion component. Same goes for `fluid.sines~` and `fluid.transients~`. For `fluid.nmf~` stuff it's obviously different, but for these it takes time to figure out what's what.

**Comment by tremblap** [comment]
always the same order: the name, then the residual!
HPSS -> H then P the resid
sine -> sines then resid
trans -> trans then resid
etc
