### ISSUE TITLE
enable relative paths for data objects' `write` message

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#20]
Whenever I call the `write` method, for example with the mlpregressor~, I get the error:

`fluid.mlpregressor~: Could not open file for writing`

I have checked the system security preferences in order to rule out some permissions, but I have given full disk access to Max. What would be a way in to debugging out any stupid decisions I may have made patching?

**Comment by weefuzzy** [comment]
First thing I'd check is the path you're trying to write, and then we can take it from there...

**Comment by jamesb93** [comment]
Do you need to pass absolute paths?

**Comment by jamesb93** [comment]
The answer is yes...

**Comment by weefuzzy** [comment]
I'll have a check of what built in objects do with relative paths and see if there's a way of getting the same behaviour for us

**Comment by jamesb93** [comment]
IIRC its relative to the top level patcher. If you hit write `foo.txt` to a coll in `~/my-patches/special-patch.maxpat` you get `foo.txt` in `~/my-patches/foo.txt`.

**Comment by jamesb93** [comment]
Not sure how much you are going via the SDK but here is the bit that describes it (obviously you know where to find this sort of stuff but I thought to get it for you): https://cycling74.com/sdk/max-sdk-8.0.3/html/chapter_files.html#chapter_files_writing_files 🙏

**Comment by tedmoore** [comment]
I believe I am having this issue again. I did find that using an absolute path works for me.

Here you can see my errors when i just had [write tedsynth.json] in the message. 

When I made it the message you see at the bottom is when the saving worked for me.

(the "extra arguments for message" warning you see in the console is from me not putting the quotes around my path)

<img width="1792" alt="Screen Shot 2021-11-07 at 10 13 13 PM" src="https://user-images.githubusercontent.com/1531144/140662051-17622f4e-a0c1-4fe6-a4a2-206982f86d5e.png">
