### ISSUE TITLE
pitch helpfile 2nd tab - load error

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#201]
it loads the piano by default overriding the example with scratchy synth and not working at all - polyphonic piano doesn't reach 98% confidence.

**Comment by jamesb93** [comment]
> it loads the piano by default overriding the example with scratchy synth and not working at all - polyphonic piano doesn't reach 98% confidence.

Because I use `Cmd+Shift+H` to load the help file I miss these problems. A really annoying behaviour by Max to disable `loadbangs` when you you have Cmd+Shift held down... 

Fixes applied in #204.
