### ISSUE TITLE
ampslice: start playing nicol on load in first tab

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#202]
it seems a wrong file has been pushed to dev:

-the said nicol playing issue
- threshold attrui is grey
- window doesn't fit (we need to scroll right)
- there is a buf onsetslice in the middle of the window

**Comment by jamesb93** [comment]
> it seems a wrong file has been pushed to dev:
> 
> -the said nicol playing issue
> 
> * threshold attrui is grey
> * window doesn't fit (we need to scroll right)
> * there is a buf onsetslice in the middle of the window

I got bitten by the two-windows-of-the-same-patch-open-in-Max-save-badness...

Fixes applied in #204.

**Comment by tremblap** [comment]
bufampslice still plays on opening. and so does bufnovelty. How to reproduce:

open the helpfile
switch the audio
it plays the whole file

prefered behaviour: it plays only when we give an int to the player, no?

**Comment by tremblap** [comment]
bufonsetslice does it too.

maybe we should not use groove and instead use play~ - so the poor user is not bombarded with sounds right away.

**Comment by jamesb93** [comment]
All fixed in #210.

Thanks
