### ISSUE TITLE
bufspectralshape: first tab: dictionary not populated

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#206]
there are no errors in the max window

**Comment by tremblap** [comment]
but the dict.view is empty

**Comment by jamesb93** [comment]
This is not a bug but maybe unexpected. You won't get a view on any of the stats till you scrub through the sound file (step 3).

**Comment by tremblap** [comment]
maybe we could send a message to the scrolling head to read the first index?

**Comment by jamesb93** [comment]
I think it is fine as it is: the instructions are clear on what to do and an empty window is not too heinous in terms of UX.
