### ISSUE TITLE
fluid.bufampslice~ musical example plays loads of clicks

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#208]
The `p "pick a slice"` subpatch plays from the start of a slice until the next, meaning that the end of each slice contains a tiny moment of the start of the next slice, leaving a click.

Shaving 100 samples off the end makes it sound much better (and makes sense since this patch isn't trying to demonstrate _off_sets).

![Screenshot 2022-05-13 at 9 46 30 pm](https://user-images.githubusercontent.com/2747015/168387098-c76be324-59cb-46fc-a22f-746818506aa8.png)

**Comment by jamesb93** [comment]
This is no longer the same file.
