### ISSUE TITLE
compiling a single object?

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#21]
Is it possible to compile only a single object from the repository? I intend to make a few buffer manipulation objects and I feel like this would help speed up the iteration between compile/rerun max.

**Comment by tremblap** [comment]
Yes! if you use ninja, just type ```ninja TARGET``` like ```ninja fluid.bufcompose_tilde``` and voilà!

**Comment by jamesb93** [comment]
This is cool, thanks! I'll give it a go.

**Comment by jamesb93** [comment]
It should be for noted for anyone who reads in the future, that `cmake` has to be directed to create the `ninja` build files by passing `-GNinja` to the initial `cmake` invocation.

**Comment by weefuzzy** [comment]
Just to add, this works with any CMake generator, not just ninja. For the IDE targets like XCode or MSVC, you can do it easily in the IDE itself, or from the command line run `cmake --build . --target <thingy>`  (https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project)
