### ISSUE TITLE
No reference files for fluid.buf2list and fluid.list2buf

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#215]
With the newschool method of doing stuff, as well as having to concatenate buffers manually (without counting indices) these objects are a lot more "core" in their usage now.

So they should probably have (mini) reference files and/or fuller documentation (e.g. I didn't know you could set the max size of `fluid.buf2list` as per #213).

**Comment by jamesb93** [comment]
The aim is to have these by beta7!

**Comment by jamesb93** [comment]
As an aside there is a little bit of cruft introduced in our plumbing when dealing with anything one-off (objects specific only to Max) because `flucoma-docs` is designed to deal with documentation. We should have it sorted though.

**Comment by jamesb93** [comment]
Solved with merge of https://github.com/flucoma/flucoma-max/pull/250
