### ISSUE TITLE
`fluid.plotter` should instantiate with `@border 0`

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#239]
Very minor point here, but the border on the default `jsui` objects looks suuuper Max 4. I don't know if this is something that is settable with the package, but it would look much nicer if it defaulted to having the `@border` off:
 
![Screenshot 2022-05-30 at 6 46 47 pm](https://user-images.githubusercontent.com/2747015/171040612-64e8c84c-e959-4f34-ab9b-a7cbfbebb19b.png)

**Comment by jamesb93** [comment]
I agree it looks nicer.

**Comment by jamesb93** [comment]
It does now.

https://github.com/flucoma/flucoma-max/pull/242

**Comment by rconstanzo** [comment]
This appears to have reverted with the latest release.

Look at all of these sad plotters in the `fluid.normalize~` helpfile:
![Screenshot 2022-06-21 at 12 58 52 pm](https://user-images.githubusercontent.com/2747015/174793951-eed7938d-22dd-4c57-8fdf-1fd725229bf3.png)

**Comment by jamesb93** [comment]
It was never updated and is fixed on the development branch.
