### ISSUE TITLE
8.2 Max SDK code signs while building

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#24]
This is perhaps more esoteric but when building with the new 8.2 SDK the binaries get code signed automatically. I'm not sure where this occurs but if I make intel binaries with the old sdk this does not happen.

I can verify this by running `codesign -dv --verbose=4 path/to/mxo` on the binaries. When I use the new SDK the binaries are signed with what seems to be a bogus identifier matching the name of the external. Max infinitely complains about not being able to load the external due to system security. I can fix this by running:

`codesign --remove-signature path/to/mxo`

Just flagging this now as something to test and to perhaps work around.

**Comment by AlexHarker** [comment]
Code signing is extremely likely to be anything to do with the SDK (I noticed that you mentioned you recently set up a new profile on the Max forum which is likely the culprit). I have not seen any change of behaviour with the new SDK and this is to do with Xcode setup, particularly as flucoma uses custom CMake scripts.

**Comment by jamesb93** [comment]
I assume as much. I should try deleting the signature in Xcode and recompiling after that. I am using `-GNinja` FWIW.

**Comment by AlexHarker** [comment]
There are several layers of settings in XCode from the OS defaults through the project and then various targets/config files. The default at OS level is probably to use any available profiles if nothing is being set explicitly.
