### ISSUE TITLE
Multiple typos in `fluid.knnclassifier~` reference page

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#244]
The subheading should be "k-nearest neighbours" (with hyphen and no caps).

I don't think the "nearest-neighbour" in the description should be hyphenated.

The URL in the Description section should be a hyperlink (perhaps just saying "click here to read more").

Although not a typo per-se, I don't know what the `@weight` attribute does from the description here.

Tons of the arguments show up as `Unknown Type`, which I imagine is a typo/flag missing on building the reference doc?

For the `fit` message, it could be clearer about "need to be the same size" (of points, columns, everything?).

For the `predict` message, the sentences all begin lowercase (as opposed to uppercase in `fit`).

There's weird/broken formatting for the `predictpoint` message:
`<o>buffer~</o>`

**Comment by tremblap** [comment]
some of it sorted in the next nightly.

**Comment by jamesb93** [comment]
Solved in https://github.com/flucoma/flucoma-max/issues/244.
