### ISSUE TITLE
@blocking 0 cancellation causes object to become unselectable in GUI

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#263]
Since the progress bars have started to be drawn on top of buffer processors calling the `cancel` method renders the object unselectable.

<pre><code>
----------begin_max5_patcher----------
407.3ocqTFsaBBCEF9Z3onoWyL.BHtq78XwrTfhqNrkzVbZL5y9ZOEh5zoKN
ufRN+8.+86bNvNeObgXCUgQuhdC44sy2yCjrBd8wd3UjMkMDEjFdEUoHKn3.
2dZ5FMnWzUWSkHkrbXqVht7CFew6RZo1YQZ5nv.TT3D6szb6Zb7nPz79Gg2s
hwanZvp3ihhN8fZTuJqBrUTr7k7AGcoo21Rc1gwn41c166aWB9mHVR3kzlaf
2zH.uD.rjwOI7xdx3woeYdsWPWcSGqZjoMxWUe.MqtVqLlY.TgFGOIKGEEmi
lUzHJ+zHhBueadZFTAljb6BQzUKDIWVHh+8BQvIWOyhhap9fcrFsTvWzrcDg
UeWz6K.QoOB4wWRdzuRdcifnsXWP3KNGcvSbCi+yOvgisU+75gRzIKGdu8Cd
nim7JpxLMPzLA+jbhc4b0J9e0m7GxGGdj110TopOYvBSicoPZCyCfPF2ENFB
kz0rg7CAEhzzE0lVXmDNV3MYIX2iJpnRdGCZV9V3LVBCMbh4uDsDGGvrk+d+
u8rEBAF
-----------end_max5_patcher-----------
</code></pre>

If you process the source buffer in this patch and click cancel before its done you will find you are no longer able to adjust the attributes in the box for example because it is unselectable.

You can grab the object by drawing a box over it but thats a nasty workaround.

I'm unaware if this is a problem with the Max API or the way that progress is implemented in the object. Either way, I raised it here to rule FluCoMa's end out first to follow up with a C74 report or to address a problem we have control over.

**Comment by weefuzzy** [comment]
Should be fixed by 078bf8e77ab309358980bcaeeb682234c08fefaa

**Comment by jamesb93** [comment]
Seems to be fixed.
