### ISSUE TITLE
Multiple typos in `fluid.kmeans~` reference file / confusing output

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#271]
There's some similar stuff from #244 (like the `<o>buffer~</o>` thing in a couple places), but also a lot of `Unresolved lookup (KMeans....`, which I guess means there's some broken formatting somewhere as these are all broken links.

These next points aren't specific to the reference file, but they aren't clarified in there (which led me to create this issue).

I also have no idea what the extra numbers that come out from the `fitpredict` message are. The reference file says:
"...and then return the learned clustering to the passed fluid.labelset~"

Are the additional numbers "the clustering"? What does that mean?

Lastly, the outlet hover message says `fluid.kmeans~: (unused)`, which doesn't help clarify the above either.

**Comment by rconstanzo** [comment]
This `<o>buffer~</o>` thing is in just about every reference file I check. Just found it in `fluid.dataset~` as well.

Would be worth doing a search/replace across the whole reference documentation.

**Comment by rconstanzo** [comment]
> The return of `fitpredict` is the number of items in each cluster.

That makes sense. It should say that somewhere as I thought it may be the centroid of the clusters or something funky like that.

**Comment by jamesb93** [comment]
The text is not technically wrong but it omits the return values and what they mean. I think because they may change in the future, or at least that was the conceit.

**Comment by rconstanzo** [comment]
That's the thing. "learned clustering" could mean just about anything. So at least saying what it is somewhere would be super useful.

**Comment by jamesb93** [comment]
I think you are confusing the return values with the learned clustering. The learned clustering is the labelset~ that you get as an output. The number of items in each cluster is just a nice to have that may change in documentation.

**Comment by rconstanzo** [comment]
Just pointing out what the reference file says, hence the confusion.

It's kind of weird that you're given unlabelled "bonus numbers" without any context/definition though. I only noticed because it broke cascading as the next stuff took the "bonus numbers" as extra arguments.

**Comment by rconstanzo** [comment]
Maybe that could be put onto the `fit` message instead to address the differentiation between "chainable" messages and "info getting" messages (similar to the issues with `fluid.pca~`s [interface](https://discourse.flucoma.org/t/ways-to-test-the-validity-usefulness-salience-of-your-data/841/49)).

**Comment by jamesb93** [comment]
This is the living contention, which is why it's not documented (otherwise we have to go back and un-document it).
