### ISSUE TITLE
Chroma help file has redundant argument & attribute

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#272]
on the "some more detail tab" it both sets 19 chroma as an argument and an attribute:
<img width="705" alt="Screenshot 2022-06-15 at 12 25 31" src="https://user-images.githubusercontent.com/1531144/173816286-fd51489d-4358-4cbc-8eb8-7b0616e5f98f.png">

**Comment by rconstanzo** [comment]
I don't know how the algorithm of `fluid.chroma~` works, but is it not similar to how `fluid.mfcc~` works where you set the argument as your maximum, then the @attribute as your actual?

**Comment by jamesb93** [comment]
Solved in #284
