### ISSUE TITLE
BufCompose example code has confusing buttons

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#273]
In the subsections tab, the "Source 1", "Source 2", and "Mixture" buttons don't stay lit when I click on them and because of the way the subsections are copied into the buffer I was at first quite confused if the buttons were working properly (it sounds like it plays "Source 1" for a second and jumps back to "Source 2", which *are* the sounds it's making but because the colors don't stay on it seems like it's not playing "Mixture", but just jumping back to playing "Source 2") 

I think just having the color of the buttons stay on is sufficient to clarify what is happening

https://user-images.githubusercontent.com/1531144/173821234-96bb5ff2-7f79-4921-b1c0-3bb6317671ad.mov

**Comment by jamesb93** [comment]
That necessitates writing a bit of code that then tracks whether or not a specific buffer is being played. I think that its fine as it personally.

**Comment by rconstanzo** [comment]
You could just do it in a different way completely, maybe even have the output dump to a `playlist~` object, which has exclusive playback natively. It also has the benefit of being able to see the waveforms, select a bit of it to play/loop etc...
