### ISSUE TITLE
BufCompose example tab multichannel plays only one channel

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#274]
I think it is doing multichannel copying and such but the play~ at the bottom is only sending one channel to the dac!
<img width="818" alt="Screenshot 2022-06-15 at 13 15 23" src="https://user-images.githubusercontent.com/1531144/173824545-adfee555-c262-41c4-9042-056efc52cbb1.png">

**Comment by jamesb93** [comment]
Solved in 458f873
