### ISSUE TITLE
fluid.bufselectevery~ help file requests @numderivs 3, which isn't possible

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#277]
This help file demonstrates setting @numderivs to 3, however the c++ allows a maximum of 2, so it should be changed to a 2.

<img width="1015" alt="Screenshot 2022-06-16 at 11 36 58" src="https://user-images.githubusercontent.com/1531144/174052561-180e9fb6-45e8-4a30-bce1-02a336daeb86.png">

![Screenshot 2022-06-16 at 11 39 30](https://user-images.githubusercontent.com/1531144/174052956-c4cd90b8-76b4-47b6-91f8-7cad6cf53e5d.png)

**Comment by jamesb93** [comment]
Solved in a78a5ba
