### ISSUE TITLE
fluid.dataset~ help file says wrong outlet

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#279]
At the bottom of the fluid.dataset~ help file it says the phrase "right outlet" which (as of beta7) is now the left outlet.
![Screenshot 2022-06-16 at 15 38 20](https://user-images.githubusercontent.com/1531144/174094788-786647b1-26af-4196-b253-882edc400026.png)

**Comment by jamesb93** [comment]
Solved in 01abf417f03bed27347e3e947da6524f6b4ef91d
