### ISSUE TITLE
fluid.spectralshape~ help file has a spectroscope~ that isn't attached to anything

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#283]
It seems to have been disconnected at some point!
<img width="1324" alt="Screenshot 2022-06-16 at 16 27 03" src="https://user-images.githubusercontent.com/1531144/174105385-abb69e53-f335-4bbb-93c2-8cf92a7476f8.png">

**Comment by jamesb93** [comment]
Solved in 4ca6deb
