### ISSUE TITLE
fluid.onsetslice~ help file can't select FMTri-M

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#286]
For some reason, this file is not selectable.

https://user-images.githubusercontent.com/1531144/174271636-15f01169-4625-4635-96ba-2a419e350ee8.mov

**Comment by tedmoore** [comment]
The same thing seems to be happening for fluid.bufonsetslice~ as well.

**Comment by jamesb93** [comment]
This is because the audio example no longer exists. I've updated it to the one which usurped it FMTriDist-M.wav in e27baae
