### ISSUE TITLE
fluid.datasetquery~ helpfile not merging

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#288]
I'm not sure if this is correct or incorrect behaviour, but either way the way this is worded and what it is doing confuses me.

it says, "Unlike transform, we're not obliged to add columns to the query. In this case, we can just filter dataset B based on conditions in dataset A. It is important to note that it merges the second provided dataset with the first for each identifier."

but it's not merging anything. it's just doing the first part of that description, "filter dataset B based on conditions in dataset A". Is it supposed to do some merging?

<img width="992" alt="Screenshot 2022-06-17 at 11 48 43" src="https://user-images.githubusercontent.com/1531144/174284169-91423d2a-37f1-4b28-83d3-e82b5e980956.png">

**Comment by tedmoore** [comment]
mmm. but it is only copying into the "joined" dataset points with identifiers that are in both? this might be the case, but it's kind of hard to see because all of the things that end up in "joined" are also in data set "B"

**Comment by tedmoore** [comment]
I also think something like this would be good to get a sense of why one might want to use this:
```
~src = Buffer.read(s,FluidFilesPath("Tremblay-ASWINE-ScratchySynth-M.wav"));

// take a listen
~src.play;

// make a dataset of pitch anlyses
(
~features = Buffer(s);
FluidBufPitch.processBlocking(s,~src,features:~features);
~ds_pitch = FluidDataSet(s).fromBuffer(~features);
~ds_pitch.print;
)

// select only the pitch analyses where the pitch confidence is > 0.9
(
~ds_filtered = FluidDataSet(s);
~dsq = FluidDataSetQuery(s);
~dsq.filter(1,">",0.9);
~dsq.addColumn(0);
~dsq.transform(~ds_pitch,~ds_filtered);
~ds_filtered.print;
)

// make another dataset of spectral analyses
(
FluidBufSpectralShape.processBlocking(s,~src,features:~features);
~ds_spec = FluidDataSet(s).fromBuffer(~features);
~ds_spec.print;
)

// select only the spectral analyses where the pitch confidence is > 0.9;
(
~ds_selected = FluidDataSet(s);
~dsq.clear;
~dsq.filter(1,">",0.9);
~dsq.transformJoin(~ds_pitch,~ds_spec,~ds_selected);
~ds_selected.print;
)

// or just append it all together to make one big dataset
(
~dsq.clear;
~dsq.addRange(0,2); // starting at column 0 add two columns (both of the columns in ~ds_pitch)
~dsq.transformJoin(~ds_pitch,~ds_spec,~ds_selected);
~ds_selected.print;
)

// or do it all at once:
(
~dsq.clear;
~dsq.filter(1,">",0.9); // only analyses where the pitch conf is high
~dsq.addColumn(0); // we'll take the pitch freq...
~dsq.transformJoin(~ds_pitch,~ds_spec,~ds_selected);// ... and append it to the spectral analyses
~ds_selected.print;
)
```

**Comment by jamesb93** [comment]
> mmm. but it is only copying into the "joined" dataset points with identifiers that are in both? this might be the case, but it's kind of hard to see because all of the things that end up in "joined" are also in data set "B"

I think it can be explained better. The identifiers of A which fit the filter are returned from B. (might be clearer or not...)

**Comment by jamesb93** [comment]
> I also think something like this would be good to get a sense of why one might want to use this:
> 
> ```
> ~src = Buffer.read(s,FluidFilesPath("Tremblay-ASWINE-ScratchySynth-M.wav"));
> 
> // take a listen
> ~src.play;
> 
> // make a dataset of pitch anlyses
> (
> ~features = Buffer(s);
> FluidBufPitch.processBlocking(s,~src,features:~features);
> ~ds_pitch = FluidDataSet(s).fromBuffer(~features);
> ~ds_pitch.print;
> )
> 
> // select only the pitch analyses where the pitch confidence is > 0.9
> (
> ~ds_filtered = FluidDataSet(s);
> ~dsq = FluidDataSetQuery(s);
> ~dsq.filter(1,">",0.9);
> ~dsq.addColumn(0);
> ~dsq.transform(~ds_pitch,~ds_filtered);
> ~ds_filtered.print;
> )
> 
> // make another dataset of spectral analyses
> (
> FluidBufSpectralShape.processBlocking(s,~src,features:~features);
> ~ds_spec = FluidDataSet(s).fromBuffer(~features);
> ~ds_spec.print;
> )
> 
> // select only the spectral analyses where the pitch confidence is > 0.9;
> (
> ~ds_selected = FluidDataSet(s);
> ~dsq.clear;
> ~dsq.filter(1,">",0.9);
> ~dsq.transformJoin(~ds_pitch,~ds_spec,~ds_selected);
> ~ds_selected.print;
> )
> 
> // or just append it all together to make one big dataset
> (
> ~dsq.clear;
> ~dsq.addRange(0,2); // starting at column 0 add two columns (both of the columns in ~ds_pitch)
> ~dsq.transformJoin(~ds_pitch,~ds_spec,~ds_selected);
> ~ds_selected.print;
> )
> 
> // or do it all at once:
> (
> ~dsq.clear;
> ~dsq.filter(1,">",0.9); // only analyses where the pitch conf is high
> ~dsq.addColumn(0); // we'll take the pitch freq...
> ~dsq.transformJoin(~ds_pitch,~ds_spec,~ds_selected);// ... and append it to the spectral analyses
> ~ds_selected.print;
> )
> ```

I like it, might just replace the tab with this if you wanna do it in SC.

**Comment by tedmoore** [comment]
> I like it, might just replace the tab with this if you wanna do it in SC.

I put it in the SC version already--it was from some old code I dug up and just added it. I figured if there was an uproar it would be easy to delete...but I also thought there probably wouldn't be an uproar 😺

**Comment by tremblap** [comment]
I like it (typos excluded) but I also think we need a didactic example with very few entries to show the various options. It is a complex object (especially in combination with dataset's merge with/without replacement flag) so we need simple examples to show exclusion (or not). So I'd say to add that as a further example to a simpler toy example.

**Comment by jamesb93** [comment]
Added the pitch/specshape filtering example and cleared up the explanation and added in 6fd8e83 and 41d945e respectively.
