### ISSUE TITLE
fluid.labelset~ help file typo

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#291]
The bubble with the arrow says "Generate random data to be stored in the fluid.dataset~", when it should say labelset.
<img width="692" alt="Screenshot 2022-06-17 at 17 36 07" src="https://user-images.githubusercontent.com/1531144/174340119-f6ca470b-ab4c-40a1-a9ea-45729d3119f3.png">

**Comment by jamesb93** [comment]
Thank you <3
