### ISSUE TITLE
fluid.normalize~ help file has a header that says fluid.standardize~

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#292]
The tab and header say standardize.
<img width="1508" alt="Screenshot 2022-06-17 at 17 45 09" src="https://user-images.githubusercontent.com/1531144/174341457-2f1e64a2-0288-4500-9448-5d29faa679db.png">

**Comment by tremblap** [comment]
was on my radar from Martin, fixing now

**Comment by tremblap** [comment]
fixed and also robust scaling flagged by Martin, in db7dd6898518989752d83964fedc653f8e36a653
