### ISSUE TITLE
fluid.demosound is not finding files

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#295]
strange, on the latest nightly:

sfplay~: can't find file ~/dev/flucoma/max/media/Tremblay-CEL-GlitchyMusicBoxMelo.wav

that is nothing like my path. It was working then it doesn't, a bit like what happen to Rod... was there any change in dev? it works in beta7

**Comment by jamesb93** [comment]
> strange, on the latest nightly:
> 
> sfplay~: can't find file ~/dev/flucoma/max/media/Tremblay-CEL-GlitchyMusicBoxMelo.wav
> 
> that is nothing like my path. It was working then it doesn't, a bit like what happen to Rod... was there any change in dev? it works in beta7

That is my path... will have to investigate why any variables like that seem to get cached. I suspect its a bit of rogue state in the cache dependencies thingy

**Comment by jamesb93** [comment]
I also would appreciate a bit more info, any specific help files? or can you load this in isolation and it always reproduces the same behaviour?

**Comment by jamesb93** [comment]
Regardless, I had a dig in the JSON structure and found that path was set as the prefix for the umenu object. I've removed it so hopefully that fixes it... 520ca0f
