### ISSUE TITLE
fluid family not in object help launcher

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#296]
this would be nice no?

**Comment by jamesb93** [comment]
Works for me out of the box:

![image](https://user-images.githubusercontent.com/13281862/174763018-6a983fc5-1766-479e-bf7b-279ba333845b.png)

**Comment by tremblap** [comment]
this looks great. I wish it was the case on mine.

**Comment by jamesb93** [comment]
Need more info, which commit?

**Comment by tremblap** [comment]
beta7

**Comment by jamesb93** [comment]
The `obj-qlookup.json` is missing from the release which is why it doesn't appear.

**Comment by tremblap** [comment]
I'm relieved my imagination doesn't go as far as issue filling :)

**Comment by jamesb93** [comment]
The fix in #301 should attend to this :)
