### ISSUE TITLE
`fluid.normalize~` tab "comparing scalers" seems to refer to a specific audio sample

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#298]
This tab gives you an option of audio files to load, but then the grey text underneath each seems to talk about a file in specific (or at least makes assumption on how that data behaves with each plot).

If that's the case, it should load the intended soundfile by default, or at least, it should change the wording to be more generic "Standardize produces a similar shape to the robust scaler. In some cases the outliers can still pull the entire shape....."

![Screenshot 2022-06-21 at 12 56 16 pm](https://user-images.githubusercontent.com/2747015/174793501-1cd66a9b-0f82-48c2-8c38-81ba071157d4.png)

Could also benefit from having a significantly smaller `pointsizescale` for all of them.

Lastly, a `speedlim` wouldn't hurt on the zoom outlet, as it really bogs my computer down trying to scroll with a longer audio file loaded.

**Comment by rconstanzo** [comment]
I see, it does default load. I've just gotten in the habit of manually loading files as in many helpfiles this interface typically does not load a file.

Maybe just have the file baked into a buffer directly since this is demonstrating the idea with this specific audio file. So just `buffer~ help.scalercomparison.src.really.long.name Olencki-TenTromboneLongTones-M.wav`.

**Comment by jamesb93** [comment]
Agree with this so I've implemented it on `dev`
