### ISSUE TITLE
fluid.buf2list reports zero sized buffer at instantiation

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#30]
fluid.buf2list will report that the buffer it is pointed to is zero sized when you create the object. This is not a problem, in my opinion, because you are likely to resize the buffer with analysis before you exfiltrate the list with fluid.buf2list later. The error should be reported when you send a bang to the object if indeed the buffer is still zero-sized.

## Steps to reproduce:

1. Create a new patch
2. Create a buffer with a name like `buffer~ foo`. Do not specify a size explicitly
3. Create a fluid.buf2list object like so: `fluid.buf2list @source foo`
4. Error will red in the console

**Comment by weefuzzy** [comment]
I thought @tremblap  fixed this in  a3ff9e26b09bb5ffc251dade29425a02cc35bee5

**Comment by jamesb93** [comment]
Yes. Can confirm by rebuilding with that commit pulled into my branch.
