### ISSUE TITLE
Text in fluid.umap~ help file says wrong number of dimensions

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#310]
The fluid.umap~ help file says that there are "140 values derived from MFCC analysis", but the dataset that get's loaded (fluid_corpus_mfcc.json) only has 26 columns, so I think 140 just needs to be changed to 26.
<img width="1533" alt="Screenshot 2022-06-28 at 11 49 07" src="https://user-images.githubusercontent.com/1531144/176161257-1bd9cb2e-83a3-4943-955c-093ad198a526.png">

**Comment by rconstanzo** [comment]
Unrelated, but it looks like the default `pointsizescale` and zoom settings are much better in yours that in the beta7 release. Is this something that's been updated?

![Screenshot 2022-06-28 at 12 08 06 pm](https://user-images.githubusercontent.com/2747015/176164698-6e16726b-9227-4061-ba2a-0d9c3eea477d.png)

**Comment by jamesb93** [comment]
> Unrelated, but it looks like the default `pointsizescale` and zoom settings are much better in yours that in the beta7 release. Is this something that's been updated?
> 
> ![Screenshot 2022-06-28 at 12 08 06 pm](https://user-images.githubusercontent.com/2747015/176164698-6e16726b-9227-4061-ba2a-0d9c3eea477d.png)

Nightly and version 1.0 pre-release has this fixed, as noted in the issue you raised :)

**Comment by jamesb93** [comment]
> The fluid.umap~ help file says that there are "140 values derived from MFCC analysis", but the dataset that get's loaded (fluid_corpus_mfcc.json) only has 26 columns, so I think 140 just needs to be changed to 26. <img alt="Screenshot 2022-06-28 at 11 49 07" width="1533" src="https://user-images.githubusercontent.com/1531144/176161257-1bd9cb2e-83a3-4943-955c-093ad198a526.png">

Certainly you are right. I will endeavour to have this fixed for the 1.1 release.
