### ISSUE TITLE
`fluid.datasetquery~` not moving over all entries when using `transformjoin`

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#321]
Double and triple checked this and it seems like there's a counting from zero/one bug somewhere.

Basically if I use `transformjoin` to filter one `fluid.dataset~` with a different one, it always leaves out one entry at the end.

Attached is a patch and datasets to demonstrate.
![Screenshot 2022-08-07 at 8 43 42 pm](https://user-images.githubusercontent.com/2747015/183308403-fde1cb8c-e9dd-42ae-a68e-6746c162f5ec.png)

[datasetquery bug.zip](https://github.com/flucoma/flucoma-max/files/9277384/datasetquery.bug.zip)

**Comment by rconstanzo** [comment]
Ok it looks like `join`s when the entry names are the same (indexes in this case) rather than moving over everything that satisfies the criteria.

The `coll` dataset starts from 0 and the `descriptors` one starts from 1, so it ignores 0 since that name doesn't overlap.

**Comment by tremblap** [comment]
indeed that is the expected behaviour.
