### ISSUE TITLE
segfault crash in fluid stats

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#334]
I just got that on Max, 100% reproducible but no time to chase further. Feel free to assign to me if you need me to investiate.

How to reproduce:

1. open this patch in overdrive with audio on - it is not working and moans that the input is the wrong size
2. while it is running, add to fluid.stats @autosize 0

it crash. I will compile in dev as soon as I get out of residency mode

**Comment by tremblap** [comment]
update - on the latest nightlies it is crashing even before #2 above...

**Comment by tremblap** [comment]
ok I ran in test and go this

```
Crashed Thread:        5  timer

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: ((i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))), function Block, file /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/dependencies/eigen-src/Eigen/src/Core/Block.h, line 122.
```

**Comment by weefuzzy** [comment]
I don't think you attached the patch. From the assertion, we can at least see that Eigen is being sent something the wrong size (but without the patch, I don't know what...)

**Comment by tremblap** [comment]
I managed to paste the wrong one above the first time round...

**Comment by weefuzzy** [comment]
This is on `dev`? Can't make it crash here

**Comment by tremblap** [comment]
this one crashes upon audio starting
1. start max 
2. copy this with audio off
3. start audio
<pre><code>
----------begin_max5_patcher----------
357.3ocsS1rSCCCCG+b5SQTNWlZRQrUNs2CDBk0F1xnKoJeL5XZ7rSqSJLfN
sd.NzTYW63++rcOlfHqzsBKAeO9ALBcLAg.W8NPQaDYGusrlagvHJwq5UaIo
gO4DsNv8y0dY0Lqi6r3kajVm1b.SyvK4dm1JeSfyFxQ42o8tZgCtv7n2Ftqb
iTs9IinzEDDKqXVVJlkm2+hVLGrXyxvOFSJbOtCMhPFDRZ74yPjUf95z7M4m
o.oZP.zdemRR5OR+KZB0ZekRXsuONvrKCbDQ5bf6EESj2wXk8eyZiT8xEHjd
UBKX8m4KtNfV4ZEudTDoWEQHKRsT8yUbPY89+N2Vs2TNT4XWD+k3pDVmTwcR
s5rXxCwLZmcp0gNg5v9UcB3waZ1KL1XvPI5Ffa0ldyEofoTELge1HFwd4P7v
rhvMcCJW2Txa.YQZu6VRHUckvn7xXqsCttRBKGJ9NgsgG3.1gRNk7Af2lZvR
-----------end_max5_patcher-----------
</code></pre>

**Comment by weefuzzy** [comment]
So, to confirm, you're using your Mac, running with Max 8, building with ninja from commit 025c6a1 ? 

(Still not crashing here: the only difference I have with `origin/dev` is bumping the version of Spectra, but that doesn't touch either of the objects in your patch)

**Comment by weefuzzy** [comment]
Crossed streams. https://github.com/flucoma/flucoma-max/issues/334#issuecomment-1252233965 applies to before your last post. Now I can crash

**Comment by weefuzzy** [comment]
So `@autosize` wasn't getting set properly from the box, which doesn't help. But also the optimizer seemed to be getting all enthusiastic about stuff

**Comment by weefuzzy** [comment]
Pushes to both Max and Core. See how you fare

**Comment by tremblap** [comment]
sorted on dev directly like a bandit, congrats !
