### ISSUE TITLE
@select attribute for fluid.bufloudness~ and fluid.bufstats~

### ISSUE THREAD

**Issue by walid-breidi** [flucoma/flucoma-max#340]
Hello,
I am working with Max 8.5.0 on Operating system macOS Monterey 12.5.1. Following your tutorial  "Building 2D Corpus Explorer (part3) " I realised that my fluid.bufloudness~ and fluid.bufstats~ objects do not have @select attributes as shown in the tutorial and I got an error message every time I sent these object an @select message or argument. Is this a version issue? Do I need to unistall and reinstall Flucoma even though I think I have the latest version?
Looking forward to hearing from you.
Kind regards,
Walid Breidi
wbreidi@free.fr

**Comment by tremblap** [comment]
indeed a version issue. what version do you have if you send [version] message in these objects?

**Comment by walid-breidi** [comment]
I reinstalled the package today and I still have the same problem. 
I get this reply for [version] message: 
fluid.bufstats~: Fluid Corpus Manipulation Toolkit, version 1.0.0-TB2.beta4, and
fluid.bufloudness~: Fluid Corpus Manipulation Toolkit, version 1.0.0-TB2.beta4

**Comment by tremblap** [comment]
this is a very old version! You might have 2 versions installed. Make sure to take 1.0.4. You can use the package manager to install the latest version.

**Comment by walid-breidi** [comment]
It’s strange, the Max package kept the old version and installed the new one. It works now that I deleted manually the old version.
Thank you very much.
