### ISSUE TITLE
`fluid.ampslice~` has default values outside of allowable range

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#353]
Just noticed this when instantiating a vanilla `fluid.ampslice~`:
![Screenshot 2023-01-31 at 11 11 12 pm](https://user-images.githubusercontent.com/2747015/215904964-89c0596d-365b-4715-8f66-41b1a25ae231.png)

Could also be a good time to change those default parameters to something that could be satisfied with sounds that exist in the universe!

Something like: `@floor -70 @fastrampup 10 @fastrampdown 400 @slowrampup 4410 @slowrampdown 4410 @onthreshold 15 @offthreshold 5 @minslicelength 1000` would be a fairly reasonable jumping off point.

The current default params are impossible to satisfy (as far as I can imagine):
![Screenshot 2023-01-31 at 11 19 23 pm](https://user-images.githubusercontent.com/2747015/215905989-570c785a-de5f-44f3-b478-65cac90e8a47.png)

My mini-rant aside, probably not ideal having default values throwing error messages though.

**Comment by tremblap** [comment]
which version are you on? this has been corrected ages ago!

**Comment by tremblap** [comment]
actually it has been corrected just after the last public release :) So it is sorted for the next one

**Comment by rconstanzo** [comment]
Did you update the default params too?!

**Comment by tremblap** [comment]
they are baked in. check the tip of nightlies, you'll see your message disappeared

**Comment by tremblap** [comment]
or if you meant to your desired values, then no. we can talk about the rationale again one day.

**Comment by rconstanzo** [comment]
That's what I meant, which is why I was surprised you responded so positively, hehe.

I'm not married to *those* specific values, but yeah, we can chat about it again at some point :)
