### ISSUE TITLE
Feature Request: Do not exclude Linux+Wine environments

### ISSUE THREAD

**Issue by jamshark70** [flucoma/flucoma-max#411]
### Is your feature request related to a problem? Please describe the problem.

(I'm not certain this is really a feature request... but I think I'm outside of "officially" supported environments, so it isn't exactly a bug either.)

I found just today that the FluCoMa for Max 1.0.6 includes an OS version check during initialization, and this excludes Linux+Wine environments: "Could not load package 'FluidCorpusManipulation', OS version unsupported."

I guess, first, the argument against my suggestion: Max specifies supported operating systems, and if I'm running outside of those environments, then support could not be guaranteed. So, from that perspective, you would have every right to close this issue summarily (and I wouldn't argue back if you did).

BUT: I was recently invited to do a presentation about Max at an AI audio conference. (Has to be Max, since it was at the request of a Max reseller.) FluCoMa is right on topic. But... I'm an occasional Max user (frequent SuperCollider user, and more under my belt with Pd than with Max), and I prefer working in Linux. Max works well enough under Wine for my courses, so I have no desire or interest in setting up a Windows environment only for a software package that I don't even use very often, and especially not just for a one-off demo-for-hire.

So, encountering the OS restriction, 1/ I withdrew from the demo; 2/ I wonder... is there a concrete technical reason for this restriction (e.g. calls to specific system functions that are available only in these OS versions)? If not, would it be possible to relax the restriction? While Linux+Wine isn't officially supported, I can see a benefit in allowing the software to run in as many environments as possible (or conversely, no particular benefit in preventing the software from running in certain environments, absent concrete problems).

It's all very impressive work btw -- just a bit surprised to run into this hiccup.

### Describe the solution you'd like to see.

If possible, relax the OS check.

### Describe alternatives you've considered

The alternative is to run in Windows, but I don't have access to a Windows laptop, so I couldn't exercise that option. This led to me giving up the professional opportunity.

### Additional context

"Nice to have" feature request... for my own work I'd use FluCoMa in SC or Pd. It's just one of those "why the... did they do that" things.

**Comment by tremblap** [comment]
Hello hjh!

Indeed it is a requirement of the package manager. but there is a way out - you can literally download the package and rag and drop in the same folder (usually ~/Documents/Max/Packages) and it will work. We have nightlies and the official package here on the github. if that works for you, then we're sorted :)

**Comment by jamshark70** [comment]
> there is a way out - you can literally download the package and rag and drop in the same folder (usually ~/Documents/Max/Packages) and it will work

I'm afraid that it doesn't -- the Package Manager doesn't work in Wine, so I installed by downloading from Releases here and extracting the zip into Packages. "Unsupported OS" ensues.

**Comment by tremblap** [comment]
ok let's try something: to edit package-info.json in your local copy to see if it will still work. first thing is to remove the "os" entry altogether. We can't do that for the official package but it might work without it on your side?

**Comment by jamshark70** [comment]
> first thing is to remove the "os" entry altogether. We can't do that for the official package but it might work without it on your side?

This does bypass the issue -- I can create [fluid.*] objects now.
