### ISSUE TITLE
Insta-crash with `fluid.dataset~`

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#413]
### Please tell us what you were doing! You can include code and files by drag and dropping them into the text area.

Having a hard time reproducing this, but it was an insta-crash and the crash report does have some `FluidMaxWrapper` stuff in it so figured it was worth posting here.

Basically just reading a `.json` into `fluid.dataset~` crashed Max:
![Screenshot 2024-01-20 at 10 03 26 PM](https://github.com/flucoma/flucoma-max/assets/2747015/078a2162-5526-4928-8ce6-0f7a48d1167e)

```
<pre><code>
----------begin_max5_patcher----------
424.3ocqTEsaCBBE8Y8qfvyNiXcNy9UVVZPk1gQACfctzz8sO7hZ6V6VMY9f
ZtGtbObtdtbz2CmK6YZL5YzKHOui9dd.z.f2XrGtg1WTS0PZXA6cYdENvsjg
0a.XkryvPkcMsSK0RMEuwE62pXEFGCwYQgQAHBIY3ySv633vHzqi6Qz0XqSM
y.bEOh5fLezxbkAiCrOyahWBm.6o5ARF9bk3h4BMfcx2e3UvB0Yktiu.oj5D
AgL+Y8DSxD+630LAsA1AdWcGuLrsVZLL04SnxttEXqMw7ZHynw0xkpRalWf7
uaNMLsltmcsKfQKQ6ocZMmJRBqzRQv8LEitgjDW+7w6XJH+Ze7l8vMqlg3WL
9teGkTCUyLehZpaKfnPx80blSyIoq+f.4l5lbgtgsgq4heN+Cm2A7u2LzxNU
wDwSbfHyrWxzFtfZ3RwkIYmHQVccyF9hYZiqH+MSj0forkvTxUL4Zlz11CLk
dLafDqGpRBCeYAPHW3BSgPE6.eJevYioJqYwXcJcJ27dep6d.bizNFKr2J49
QZkmkRveNb2ftk5TBXi8O4+E1JdXCA
-----------end_max5_patcher-----------
</code></pre>
```

Crash report:
[dataset crash.zip](https://github.com/flucoma/flucoma-max/files/13999329/dataset.crash.zip)

```
15  fluid.libmanipulation         	       0x1773f0cb8 void fluid::client::FluidMaxWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient>>>::doDump<6ul>(fluid::client::FluidMaxWrapper<fluid::client::NRTThreadingAdaptor<fluid::client::NRTSharedInstanceAdaptor<fluid::client::dataset::DataSetClient>>>*, symbol*, short, atom*) + 692
```

### What was the expected result?

Just loading the dataset.

### What was the actual result?

Insta-crash.

### What operating system were you using?

Mac

### Operating system version

macOS 14.2

### FluCoMa Version

1.0.6

**Comment by tremblap** [comment]
looking at the crash report, and @weefuzzy or threading master @AlexHarker will confirm, it seems to be a Dict (so a Max) bug - most precisely the js interface we use in the fluid.plotter to retrieve the data.

**Comment by AlexHarker** [comment]
The crash looks like a dereferencing of a null pointer (probably representing a mutex) several levels deep within Max code and definitely with a jsui in response to a sent message.

There is no clear evidence that FluCoMa is the cause of the crash (although it can't be 100% ruled out) and with no steps to reproduce it may not be super productive to me to track this. I think the jsui is creating a dictionary as PA suggests when it crashes, so if anything that is where to look. This dictionary may well be related to what has been sent in, so it is not entirely separable from the flucoma code, but that would only makes sense (possibly) the max wrapper was dealing with dictionaries incorrectly, and even then it might be a bit of a stretch.

The relevant code is doDump() in the max wrapper. I have to be honest, it's a little hard track the code at the end of that function that deals with freeing resources, and personally I do not favour the fact that the branch on ac at the bottom of the method clearly need to match that further up - to my mind it makes it a little harder to reason about paired retain/release type calls and makes it vulnerable to errors during maintenance. I also find the call to dictobj_release(dest) prior to called object_notify () on dest quite strange [as far as I can see object_free(d) should be safe]. But I didn't write this code and this also isn't where it is crashing, so I don't see anything here to make this worth serous further pursuit.

**Comment by rconstanzo** [comment]
Is this worth kicking the ball over to c74 with the crash report? (perhaps along with the comments from this issue)

**Comment by AlexHarker** [comment]
I doubt it.The words "Having a hard time reproducing this" never make for a promising bug report unfortunately.

**Comment by rconstanzo** [comment]
That's what I imagined, but I can't read into the crash reports well enough to know matters or not. So with that I guess this issue can be bid adieu.
