### ISSUE TITLE
fluid.bufampgate~ display shows some lines that then disappear

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#54]
In the basic tab when I hit any of the options that start with 'reset' to try some different parameters the display shows some red lines that flash for a moment and then disappear. Some of the lines stay there, I just don't know what the flashes are and if I, the user, should care about them?

Is this going to be replaced with `fluid.waveform~`?

**Comment by jamesb93** [comment]
I imagine whatever is in place will be usurped by fluid.waveform~ in due time.

**Comment by jamesb93** [comment]
This is solved in the upcoming translation of SC.
