### ISSUE TITLE
fluid.sines~ help file settings don't demonstrate the object

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#55]
The sound file that loads with the helpfile is silent when I ask for just the sines out of the object. Just setting a different soundfile as the default would solve this.

My guess is that perhaps the `fluid.demosound` maxpat saves it as an index in the folder and now that we added more soundfiles that index changed and so it's just pulling up the wrong soundfile?

**Comment by jamesb93** [comment]
This has been changed in PR #83
