### ISSUE TITLE
max: doesn't understand "definesubstitution"

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#65]
Max 7 is not happy with this shortcut in the init file. @weefuzzy said it was another problem, so it is here :)

**Comment by jamesb93** [comment]
I've had a look into this too in tandem with asking @weefuzzy for help. I think it is not worth solving right now. It adds a lot of quality to life for Max 8 and the error is non-breaking for Max 7. To make it work for Max 7 too would require lots of black magic and bloat of the package in general.
