### ISSUE TITLE
`fluid.plotter` help file comments

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-max#68]
Just a couple of comments on the `fluid.plotter` help: 

* The numbers-in-bubbles paradigm we've adapted from built in help normally signals (to me) that I, as help file reader, should do something. So I find it confusing when they're just there to draw my attention to the various stages of a flow. 
* I think illustrative comments like that are better represented using a bubble
* Also, having a bunch of the numbers in circles in a funny order is more confusing than not having them at all 
* Consider making the red warning thing on tab 2 much bigger, and possibly moving that warning closer to the action for the (1): my eye went nowhere near it when running the patch, so there was a longish moment of "where's my plot??"

**Comment by jamesb93** [comment]
Actioned in: https://github.com/flucoma/flucoma-max/pull/70

**Comment by jamesb93** [comment]
@weefuzzy if you think the new and improved help file is in a good place would you be able to close this issue?
