### ISSUE TITLE
Windows: remove the file writing to \tmp in the examples

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#7]
Situation: Many DataSet examples and some help files use the (linux-biased) /tmp folder to write temporary files. On Windows that doesn't work. 

Solution: find a way that writes temp files in a system-agnostic way and replace them everywhere.

**Comment by jamesb93** [comment]
I think we can assume that after examples are curated and cleaned up this will not be an issue so I'll close it for now otherwise we'll double handle work.
