### ISSUE TITLE
Overview objects list

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-max#74]
The overview for Max currently is missing some things:

1. `fluid.grid`

2. `fluid.stats`
3. `fluid.bufstft`

We also need to agree on the headings for these as _I_ moved some around in Max as things have transformed from abstractions to full blown externals for example.

**Comment by weefuzzy** [comment]
Suggest:
1. `fluid.grid` -> analyse data -> unsupervised 
2. `fluid.stats` -> analyse data -> change 'buffer analysis' to 'statistical analysis' and bundle with `fluid.bufstats`
3. `fluid.bufstft` -> analyse audio -> buffer in, buffer out

**Comment by jamesb93** [comment]
I like it.

I also moved fluid.list2buf, but2list and scale out of helper abstractions to buffer utilities and changed the name of helper abstractions to experimental abstractions and included fluid.waveform~ and fluid.plotter. Dont know what you think about that change in taxonomy :)

**Comment by weefuzzy** [comment]
I'm very relaxed about it

**Comment by jamesb93** [comment]
🆒 😎
