### ISSUE TITLE
`fluid.waveform~`: how to `removelayer` or `clear`

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#85]
I can't seem to get the `removelayer` message to work. 

Also, is there a way to just clear the entire contents of a `fluid.waveform~`?

<img width="1424" alt="Screen Shot 2021-11-25 at 3 20 11 PM" src="https://user-images.githubusercontent.com/1531144/143497589-c79b5038-435e-4220-8590-51b4a3ad7806.png">

Thank you!

**Comment by jamesb93** [comment]
The latest version has it but it's a bit finicky to build it unless you have the environment setup. It is however actually implemented so should come in the next release.

**Comment by jamesb93** [comment]
Going to close this as other issues that eventually pull in fluid.waveform~ automagically to new builds will/would've solve/d this.
