### ISSUE TITLE
left outlet of `fluid.plotter` is labeled incorrectly in jsui somewhere

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-max#86]
It says it's the id of the nearest point. Maybe this has already been fixed, but I figured I'd flag it here for you to know rather than digging through commits...
<img width="429" alt="Screen Shot 2021-11-28 at 6 49 41 PM" src="https://user-images.githubusercontent.com/1531144/143791408-279cd865-4c3d-4679-b47c-dd53dcb6bb97.png">

**Comment by jamesb93** [comment]
That's old and should be fixed - thanks

**Comment by jamesb93** [comment]
Solved in PR #87
